import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Linkbrary</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <Link href={"/folder"}>
          <h1>FolderPage로 이동</h1>
        </Link>
        <Link href={"/share"}>
          <h1>SharePage로 이동</h1>
        </Link>
      </main>
    </>
  );
}
